GMAIL_USERNAME: 'online.restaurant.management12@gmail.com'
GMAIL_PASSWORD: 'online12345'

GOOGLE_CLIENT_ID: '880433183003-j2m91qec970dffiteooab61r89cpai64.apps.googleusercontent.com'
GOOGLE_CLIENT_SECRET: '3HzkTxFFk38Dqth_inpb8y7F'

FACEBOOK_ID: '199980420588821'
FACEBOOK_SECRET: '2eff37280bb7d2e323f51023ffae569c'